# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Negative log-likelihood and gradient for a Royston-Parmar model
#'
#' @param beta parameter vector.
#' @param X design matrix for the linear predictor eta.
#' @param dX design matrix for d(eta)/d(log t).
#' @param logtime log of observed time.
#' @param status event indicator (1 = event, 0 = censored).
#' @param scale integer scale code: 0 = PH, 1 = PO, 2 = probit.
#' @return a list with `value` (negative log-likelihood) and `gradient`.
#' @keywords internal
rp_negloglik_grad_cpp <- function(beta, X, dX, logtime, status, scale) {
    .Call(`_rpsurv_rp_negloglik_grad_cpp`, beta, X, dX, logtime, status, scale)
}

